### ISSUE TITLE
Update guava library version 33.1.0-jre

### ISSUE THREAD

**Issue by sumit-gupta-sgt** [arghya18/trino-group-provider-ldap-ad#3]
I am using trino-group-provider-ldap-ad for AD group binding, this group provider plugin uses below guava library version 30.1-jre, this guava library has so some Vulnerable which is already fixed in newer version, I am trying to upgrade guava library version to 33.1.0-jre. i can't start trino, getting below exception. 

```
java.lang.NoClassDefFoundError: com/google/common/collect/ImmutableMap
	at io.asaha.trino.groupprovider.ldap.LdapGroupProvider.<init>(LdapGroupProvider.java:100)
	at io.asaha.trino.groupprovider.ldap.LdapGroupProviderFactory.create(LdapGroupProviderFactory.java:20)
	at io.trino.security.GroupProviderManager.setConfiguredGroupProvider(GroupProviderManager.java:93)
	at io.trino.security.GroupProviderManager.loadConfiguredGroupProvider(GroupProviderManager.java:77)
	at io.trino.security.GroupProviderManager.loadConfiguredGroupProvider(GroupProviderManager.java:61)
	at io.trino.server.Server.doStart(Server.java:178)
	at io.trino.server.Server.lambda$start$0(Server.java:93)
	at io.trino.$gen.Trino_446____20240807_215650_1.run(Unknown Source)
	at io.trino.server.Server.start(Server.java:93)
	at io.trino.server.TrinoServer.main(TrinoServer.java:38)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.ImmutableMap
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
	at io.trino.server.PluginClassLoader.loadClass(PluginClassLoader.java:106)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 10 more
```

**Comment by sumit-gupta-sgt** [comment]
Issue can fixed via link to shared library
